// controllers/whatsappController.js
import dotenv from "dotenv";
dotenv.config();

import { sendInitialTemplateMessage, sendWhatsAppTextMessage, fetchMediaUrl } from "../utils/whatsappClient.js";
import decideNextStep from "../utils/aiDecisionEngine.js";
import { supabase } from "../config/supabase.js";
import * as chatCtrl from "./chatController.js"; // adjust path as needed


const convoCache = new Map();
const BUCKET_NAME = process.env.SUPABASE_BUCKET || "participant-docs";

/* ---------------------------
   Helpers
   --------------------------- */
function ensureCache(participant) {
  const pid = participant.participant_id;
  if (!convoCache.has(pid)) {
    const initial = { 
      call_status: "awaiting_rsvp", 
      currentDoc: { name: null, role: null, type: null }, 
      pendingDocs: [], 
      lastUpdated: new Date() 
    };
    convoCache.set(pid, initial);
    return initial;
  }
  return convoCache.get(pid);
}

async function ensureConversationRow(pid, eventId) {
  const { data: existing } = await supabase
    .from("conversation_results")
    .select("*")
    .eq("participant_id", pid)
    .maybeSingle();
  
  if (!existing) {
    // result_id is auto-generated by Supabase (uuid default)
    // conversation_id defaults to NULL (managed by MAKE/11labs)
    const { data: newRow, error } = await supabase
      .from("conversation_results")
      .insert({
        participant_id: pid,
        event_id: eventId,
        call_status: "awaiting_rsvp",
        last_updated: new Date().toISOString()
      })
      .select()
      .maybeSingle();
    
    if (error) {
      console.error("❌ Error creating conversation row:", error);
      throw error;
    }
    console.log("✅ Created new conversation row:", newRow);
    return newRow;
  }
  
  // If event_id is null in existing row, update it
  if (!existing.event_id && eventId) {
    const { error: updateError } = await supabase
      .from("conversation_results")
      .update({ event_id: eventId })
      .eq("participant_id", pid);
    
    if (updateError) {
      console.error("❌ Error updating event_id:", updateError);
    } else {
      console.log("✅ Updated event_id for existing conversation");
      existing.event_id = eventId;
    }
  }
  
  return existing;
}

/**
 * Upload a remote media URL into Supabase storage and return public URL.
 * Path format: participant-docs/{participantId}/{eventId}/{timestamp}_{filename}
 */
async function uploadRemoteToBucket(mediaUrl, participantId, eventId, origFilename = null) {
  try {
    if (!mediaUrl) return null;

    // WhatsApp requires AUTH header to fetch media
    const resp = await fetch(mediaUrl, {
      headers: {
        Authorization: `Bearer ${process.env.WHATSAPP_TOKEN}`
      }
    });

    if (!resp.ok) {
      console.error("❌ Failed to fetch WhatsApp media:", resp.status);
      return null;
    }

    const buffer = Buffer.from(await resp.arrayBuffer());

    const ts = Date.now();
    const safeName = origFilename
      ? origFilename.replace(/\s+/g, "_")
      : `document_${ts}`;

    // PRIVATE storage path
    const storagePath = `${participantId}/${eventId}/${ts}_${safeName}`;

    console.log("📦 Uploading private file:", storagePath);

    // Upload (bucket must be private)
    const { error } = await supabase.storage
      .from("participant-docs")
      .upload(storagePath, buffer, {
        contentType: resp.headers.get("content-type") || "application/octet-stream",
        upsert: false
      });

    if (error) {
      console.error("❌ Supabase Upload Error:", error);
      return null;
    }

    // ❗️ DO NOT RETURN PUBLIC URL
    // Return only private storage path
    return storagePath;

  } catch (err) {
    console.error("❌ uploadRemoteToBucket error:", err);
    return null;
  }
}



/* ---------------------------
   Save upload row helper
   --------------------------- */
async function saveUploadRow({ participant_id, participant_relatives_name, document_url, document_type, role }) {
  try {
    // upload_id is auto-generated by Supabase (uuid default)
    const { data, error } = await supabase.from("uploads").insert({
      participant_id,
      participant_relatives_name: participant_relatives_name || null,
      document_url: document_url || null,
      document_type: document_type || "Document",
      role: role || "Self",
      proof_uploaded: true,
      created_at: new Date().toISOString()
    }).select();

    if (error) {
      console.error("❌ Error inserting upload row:", error);
      return null;
    }

    console.log("✅ Upload row saved:", data);
    return data;
  } catch (err) {
    console.error("❌ saveUploadRow error:", err);
    return null;
  }
}

/* ---------------------------
   Webhook verify (Meta)
   --------------------------- */
export const verifyWebhook = (req, res) => {
  const verify_token = process.env.WHATSAPP_VERIFY_TOKEN;
  const mode = req.query["hub.mode"];
  const token = req.query["hub.verify_token"];
  const challenge = req.query["hub.challenge"];
  
  if (mode && token) {
    if (mode === "subscribe" && token === verify_token) {
      return res.status(200).send(challenge);
    } else {
      return res.sendStatus(403);
    }
  }
  return res.sendStatus(400);
};

/* ---------------------------
   Main webhook: handleIncomingMessage
   --------------------------- */
export const handleIncomingMessage = async (req, res) => {
  console.log("🔹 FULL WHATSAPP PAYLOAD:", JSON.stringify(req.body, null, 2));

// Extract value block
const value = req.body.entry?.[0]?.changes?.[0]?.value;

// 🔹 1. Ignore delivery/read/template statuses
if (value?.statuses) {
  console.log("ℹ️ Status notification received:", value.statuses[0]?.status);
  return res.sendStatus(200);
}

// 🔹 2. Ignore non-message payloads
if (!value?.messages) {
  console.log("⚠️ No messages field in webhook (not a user message)");
  return res.sendStatus(200);
}

  try {
    const message = value?.messages?.[0];
    // Detect BOT / TEMPLATE message (sent from your business number)
const businessNumber = process.env.WHATSAPP_BUSINESS_NUMBER; // e.g., "14155238886"
if (message.from === businessNumber && message.type === "text") {
  const templateText = message.text?.body || "";

  // Find participant via recipient number
 const to = message.to || message.recipient_id || null;


  if (to) {
    // Lookup participant
    const { data: participant } = await supabase
      .from("participants")
      .select("participant_id, full_name, event_id")
      .eq("phone_number", to)
      .maybeSingle();

    if (participant) {
      const chat = await chatCtrl.ensureChat({
        event_id: participant.event_id,
        phone_number: to,
        person_name: participant.full_name
      });

      // Save BOT/template message to DB
      await chatCtrl.saveMessage({
        chat_id: chat.chat_id,
        sender_type: "ai",
        message: templateText,
        message_type: "text",
        media_path: null
      });

      console.log("💾 Auto-saved template message:", templateText);
    }
  }

  // Prevent double processing — STOP here for templates
  return res.sendStatus(200);
}

    if (!message) return res.sendStatus(200);

    const from = message.from;
    const incomingType = message.type || "text";



    // Normalize userText (buttons treated as text)
    let userText = message.text?.body?.trim() ?? "";
    if (incomingType === "button") {
      userText = message?.button?.payload || message?.button?.text || userText;
    }

    // Detect media id + original filename
    let mediaId = null;
    let origFilename = null;
    if (incomingType === "image" || incomingType === "document" || incomingType === "video") {
      mediaId = message[incomingType]?.id || null;
      origFilename = message.document?.filename || null;
    }

    // Check webhook-provided temporary public url
    let mediaUrl = message.image?.url || message.document?.url || message.video?.url || null;

    // Exchange mediaId -> url if needed
    if (!mediaUrl && mediaId && typeof fetchMediaUrl === "function") {
      try {
        mediaUrl = await fetchMediaUrl(mediaId);
      } catch (err) {
        console.warn("fetchMediaUrl failed:", err);
      }
    }

    console.log("📩 Incoming:", { 
      from, 
      incomingType, 
      preview: (userText || "").slice(0, 120), 
      mediaUrl: mediaUrl ? "YES" : "NO", 
      mediaId 
    });

    
    

    // Lookup participant
    const { data: participant } = await supabase
      .from("participants")
      .select("*")
      .eq("phone_number", from)
      .maybeSingle();
    
    if (!participant) {
      console.warn("⚠️ Participant not found for phone:", from);
      return res.sendStatus(200);
    }

    const { data: uploadedDocuments } = await supabase
  .from("uploads")
  .select("*")
  .eq("participant_id", participant.participant_id);


    const displayName = participant.full_name?.trim() || "Guest";
    const pid = participant.participant_id;
    const eventId = participant.event_id;

    // Ensure conversation row exists
    let convo = await ensureConversationRow(pid, eventId);

    // Ensure cache
    const cache = ensureCache(participant);
    const callStatus = cache.call_status || convo.call_status || "awaiting_rsvp";

    // If we have mediaUrl, upload into supabase bucket for long term storage
    let storedMediaPath = null;
if (mediaUrl) {
  try {
    console.log("📤 Uploading media to bucket...");
    const uploadedPath = await uploadRemoteToBucket(
      mediaUrl, 
      pid, 
      eventId, 
      origFilename || `${displayName.replace(/\s+/g, "_")}_${incomingType}`
    );

    storedMediaPath = uploadedPath; // ✅ only store private path
    console.log("✅ Media stored at:", storedMediaPath);
  } catch (err) {
    console.error("❌ Failed to upload media to bucket:", err);
    storedMediaPath = null;
  }
}



    // Delegate entire decision to AI engine
    let decision;
    try {
      decision = await decideNextStep({
        userMessage: userText || "",
        callStatus,
        participant,
        convo,
        cache,
        event: { event_name: await getEventName(eventId) || "Event" },
        incomingMediaUrl: storedMediaPath|| null,
         uploadedDocuments 
      });
    } catch (aiErr) {
      console.error("❌ AI error (decideNextStep):", aiErr);
      
      await sendWhatsAppTextMessage(
        from, 
        `${displayName}, sorry — I'm having trouble processing that right now. Could you try again in a moment?`
      );
      return res.sendStatus(200);
    }

    // Validate decision shape
    if (!decision || typeof decision !== "object") {
      console.warn("AI returned invalid decision object:", decision);
      await sendWhatsAppTextMessage(
        from, 
        `${displayName}, sorry — I couldn't understand that. Could you rephrase?`
      );
      return res.sendStatus(200);
    }

    const replyToSend = decision.reply ?? `Sorry ${displayName}, I couldn't process that. Could you please rephrase?`;
    const nextState = decision.nextState ?? callStatus;
    const actions = decision.actions ?? { updateDB: false, fields: {} };

    console.log("🤖 AI Decision:", {
      nextState,
      updateDB: actions.updateDB,
      fields: actions.fields,
      saveUpload: actions.saveUpload ? "YES" : "NO",
      cacheUpdate: actions.cacheUpdate ? "YES" : "NO"
    });

    // 1) Update cache if AI requested cache updates (for document flow)
    if (actions.cacheUpdate) {
      if (actions.cacheUpdate.currentDocName !== undefined) {
        cache.currentDoc.name = actions.cacheUpdate.currentDocName;
      }
      if (actions.cacheUpdate.currentDocRole !== undefined) {
        cache.currentDoc.role = actions.cacheUpdate.currentDocRole;
      }
      if (actions.cacheUpdate.currentDocType !== undefined) {
        cache.currentDoc.type = actions.cacheUpdate.currentDocType;
      }
      console.log("💾 Cache updated:", cache.currentDoc);
    }

    // 2) Save upload to uploads table if requested
    let uploadResult = null;
    if (actions.saveUpload && storedMediaPath) {
      try {
       const uploadUrl = actions.saveUpload.document_url === "MEDIA"
  ? storedMediaPath  // ✅ private path
  : actions.saveUpload.document_url;


        uploadResult = await saveUploadRow({
          participant_id: pid,
          participant_relatives_name: actions.saveUpload.participant_relatives_name ?? participant.full_name,
          document_url: uploadUrl,
          document_type: actions.saveUpload.document_type ?? "Document",
          role: actions.saveUpload.role ?? "Self"
        });

        console.log("✅ Upload saved to uploads table");
      } catch (err) {
        console.error("❌ Error inserting upload row:", err);
      }
    }

    // 3) Update conversation_results - ALWAYS update at minimum the call_status
    try {
      // Check if row exists first to get current event_id
      const { data: existingRow } = await supabase
        .from("conversation_results")
        .select("result_id, event_id")
        .eq("participant_id", pid)
        .maybeSingle();

      const fieldsToUpdate = {
        call_status: nextState,
        last_updated: new Date().toISOString(),
        event_id: existingRow?.event_id || eventId // Preserve existing event_id or use current one
      };

      // Add AI-provided fields if updateDB was requested
      if (actions.updateDB && actions.fields) {
        Object.keys(actions.fields).forEach(key => {
          fieldsToUpdate[key] = actions.fields[key];
        });
      }

      // If media was uploaded, update document_url and proof_uploaded
   if (storedMediaPath) {
  fieldsToUpdate.document_url = storedMediaPath;  // ✅ private path
  if (actions.fields?.proof_uploaded !== false) {
    fieldsToUpdate.proof_uploaded = true;
  }
}


      // Link upload_id if we just created an upload
      if (uploadResult && uploadResult[0]?.upload_id) {
        fieldsToUpdate.upload_id = uploadResult[0].upload_id;
        console.log("🔗 Linking upload_id to conversation_results:", uploadResult[0].upload_id);
      }

      console.log("💾 Updating conversation_results:", fieldsToUpdate);

      if (existingRow) {
        // UPDATE existing row
        const { data: updateData, error: updateError } = await supabase
          .from("conversation_results")
          .update(fieldsToUpdate)
          .eq("participant_id", pid)
          .select();

        if (updateError) {
          console.error("❌ Error updating conversation_results:", updateError);
        } else {
          console.log("✅ Conversation results updated:", updateData);
        }
      } else {
        // INSERT new row (include event_id)
        const { data: insertData, error: insertError } = await supabase
          .from("conversation_results")
          .insert({
            participant_id: pid,
            event_id: eventId,
            ...fieldsToUpdate
          })
          .select();

        if (insertError) {
          console.error("❌ Error inserting conversation_results:", insertError);
        } else {
          console.log("✅ Conversation results inserted:", insertData);
        }
      }
    } catch (err) {
      console.error("❌ Error saving to conversation_results:", err);
    }

    // Update local cache
    cache.call_status = nextState;
    cache.lastUpdated = new Date();
    convoCache.set(pid, cache);

    // Personalize reply and send
    let finalReply = replyToSend;
    if (!finalReply.toLowerCase().includes(displayName.toLowerCase())) {
      finalReply = `${displayName}, ${finalReply}`;
    }
    
    await sendWhatsAppTextMessage(from, finalReply);

    // ensure chat exists
const chat = await chatCtrl.ensureChat({
  event_id: eventId,
  phone_number: from,
  person_name: displayName
});

// Save the incoming user message (user -> ai)
await chatCtrl.saveMessage({
  chat_id: chat.chat_id,
  sender_type: "user",
 message: userText || (mediaUrl ? `[${incomingType.toUpperCase()}]` : "TEXT"),
  message_type: incomingType || "text",
  media_path: storedMediaPath // private path if media uploaded
});
// Persist AI reply in messages table
await chatCtrl.saveMessage({
  chat_id: chat.chat_id,
  sender_type: "ai",
  message: finalReply || "AI reply",
  message_type: "text",
  media_path: null
});


    return res.sendStatus(200);
  } catch (err) {
    console.error("❌ Handler Error:", err);
    
    try {
      const message = value?.messages?.[0];
      // Detect BOT / TEMPLATE message (sent from your business number)
// Ignore template / business messages completely
const businessNumber = process.env.WHATSAPP_BUSINESS_NUMBER;
if (message.from === businessNumber) {
  console.log("ℹ️ Ignored outgoing template/business message");
  return res.sendStatus(200);
}


      const from = message?.from;
      if (from) {
        await sendWhatsAppTextMessage(from, `Apologies — an error occurred. Please reply again.`);
      }
    } catch (e) {
      console.error("❌ Failed fallback send:", e);
    }
    
    return res.sendStatus(500);
  }
};

/* ---------------------------
   Helper: get event name
   --------------------------- */
async function getEventName(eventId) {
  try {
    const { data } = await supabase
      .from("events")
      .select("event_name")
      .eq("event_id", eventId)
      .maybeSingle();
    return data?.event_name ?? null;
  } catch (e) {
    return null;
  }
}

/* ---------------------------
   Start initial message (template)
   --------------------------- */
export const startInitialMessage = async (req, res) => {
  try {
    const { event_id } = req.body;
    if (!event_id) return res.status(400).json({ error: "Event ID is required" });

    const { data: participants, error } = await supabase
      .from("participants")
      .select("participant_id, full_name, phone_number, event_id")
      .eq("event_id", event_id);
    
    if (error) throw error;

    for (const person of participants) {
      let phone = person.phone_number.toString().trim();
      if (!phone.startsWith("91")) phone = "91" + phone;
      
      const templateComponents = [
        { type: "body", parameters: [{ type: "text", text: person.full_name || "Guest" }] }
      ];
      
      await sendInitialTemplateMessage(phone, "invite_rsvp", templateComponents);

      // Ensure conversation row exists (result_id auto-generated, conversation_id NULL)
      const { data: existingConvo } = await supabase
        .from("conversation_results")
        .select("result_id")
        .eq("participant_id", person.participant_id)
        .maybeSingle();

      if (!existingConvo) {
        await supabase.from("conversation_results").insert({
          participant_id: person.participant_id,
          event_id: person.event_id,
          call_status: "awaiting_rsvp",
          last_updated: new Date().toISOString()
        });
      }

      convoCache.set(person.participant_id, { 
        call_status: "awaiting_rsvp", 
        currentDoc: { name: null, role: null, type: null }, 
        pendingDocs: [], 
        lastUpdated: new Date(), 
        event_id: person.event_id 
      });
    }

    return res.json({ 
      success: true, 
      message: "✅ Initial messages triggered successfully!" 
    });
  } catch (err) {
    console.error("❌ WhatsApp Send Error:", err?.response?.data || err);
    return res.status(500).json({ error: "WhatsApp send failed" });
  }
};

/* ---------------------------
   Batch send (frontend) — invite_rsvp template
   --------------------------- */
export const sendBatchInitialMessage = async (req, res) => {
  try {
    const { event_id, filter_null_rsvp } = req.body;
    if (!event_id) return res.status(400).json({ error: "event_id required" });

    const { data: participants, error: participantsError } = await supabase
      .from("participants")
      .select("participant_id, full_name, phone_number, event_id")
      .eq("event_id", event_id);
    
    if (participantsError) {
      console.error("❌ Error fetching participants:", participantsError);
      return res.status(500).json({ error: "Failed to fetch participants" });
    }

    if (!participants || participants.length === 0) {
      return res.status(404).json({ error: "No participants found" });
    }

    let targetParticipants = participants;
    
    if (filter_null_rsvp) {
      const { data: conversations } = await supabase
        .from("conversation_results")
        .select("participant_id, rsvp_status")
        .eq("event_id", event_id);
      
      const rsvpMap = new Map();
      (conversations || []).forEach(c => rsvpMap.set(c.participant_id, c.rsvp_status));
      
      targetParticipants = participants.filter(p => {
        const status = rsvpMap.get(p.participant_id);
        return !status || status === null || status === "";
      });
    }

    if (targetParticipants.length === 0) {
      return res.status(200).json({ 
        message: "No participants need messages", 
        sent_count: 0 
      });
    }

    let successCount = 0, failCount = 0;
    
    for (const p of targetParticipants) {
      try {
        let phone = p.phone_number?.toString().trim();
        if (!phone) throw new Error("Missing phone number");
        if (!phone.startsWith("91")) phone = "91" + phone;

        const name = p.full_name?.trim() || "Guest";
        const templateName = "invite_rsvp";
        const templateComponents = [
          { type: "body", parameters: [{ type: "text", text: name }] }
        ];

        await sendInitialTemplateMessage(phone, templateName, templateComponents);

        // Ensure conversation row exists
        const { data: existingConvo } = await supabase
          .from("conversation_results")
          .select("result_id")
          .eq("participant_id", p.participant_id)
          .maybeSingle();

        if (!existingConvo) {
          await supabase.from("conversation_results").insert({
            participant_id: p.participant_id,
            event_id: p.event_id,
            call_status: "awaiting_rsvp",
            last_updated: new Date().toISOString()
          });
        }

        convoCache.set(p.participant_id, { 
          call_status: "awaiting_rsvp", 
          currentDoc: { name: null, role: null, type: null }, 
          pendingDocs: [], 
          lastUpdated: new Date(), 
          event_id: p.event_id 
        });
        
        successCount++;
      } catch (err) {
        failCount++;
        console.error(`❌ Failed to send template to ${p.phone_number}:`, err.message || err);
      }
    }

    console.log(`📊 Batch Results: ${successCount} sent, ${failCount} failed`);
    
    return res.json({ 
      message: "✅ Batch initial RSVP messages sent", 
      template_used: "invite_rsvp", 
      total_targeted: targetParticipants.length, 
      sent_count: successCount, 
      failed_count: failCount, 
      filtered_by_null_rsvp: !!filter_null_rsvp 
    });
  } catch (err) {
    console.error("❌ sendBatchInitialMessage error:", err);
    return res.status(500).json({ error: "Failed to send batch messages" });
  }
};